### ISSUE TITLE
input in chained instructions is broken

### ISSUE THREAD

**Issue by int-e** [Helen0903/bitch#1]
As far as I understand it, the program `\/#0|\/\/` is supposed to print the first three inputs. However, this doesn't quite work:

```
$ cat test
\/#0|\/\/
$ echo 1 2 3 | java bitch test
1
-1
2
$ ( echo 1 2; sleep 1; echo 3 ) | java bitch test
1
3
2
```

The main problem appears to be that each instance of `Program` creates a new `Scanner` that attempts to consume input from `System.in`. These scanners interact badly: due to buffering, each scanner tends to consume more than one input at a time, and once the first scanner is destroyed, `System.in` will be closed.

Relevant code: [bitch.java#L61](../blob/0969cec0e98fee178d5ac8b832f98955c7b9c243/bitch.java#L61).

Relatedly, why don't you use [`Scanner.nextLong`](https://docs.oracle.com/javase/7/docs/api/java/util/Scanner.html#nextLong()) to read the next number, which would allow several lines of input to be read?

**Comment by Helen0903** [comment]
I'm alive sorry just terribly slow at everything.

I'm rewriting this interpreter, I'll fix that (and hopefully a lot more) when I push.

**Comment by Helen0903** [comment]
I thought I had fixed it with the last update but apparently not. Missing a single `static` for the scanner!

This will probably not get the redo it desperately needs, but at least now it should be functional.
